title: My Personal Site
description: My personal website

url: "commandhat.github.io"
baseurl: "/blogsite-withpages"

markdown: kramdown

collections:
  blog:
    output: true
    permalink: /blog/:path/

  projects:
    output: true
    permalink: /projects/:path/

  roblox:
    output: true
    permalink: /roblox/:path/

  about:
    output: true
    permalink: /about/:path/

plugins:
  - jekyll-feed
  - jekyll-archives-v2
  - jekyll-webp
  - jekyll-youtube
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

feed:
  collections:
    blog:
      path: "/blog/feed.xml"
    roblox:
      path: "/roblox/feed.xml"

jekyll-archives:
  roblox:
    enabled:
      - tags
    layouts:
      tags: roblox-tag
    permalinks:
      tags: /roblox/tags/:name/